name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Update APT sources
      run: sudo apt update
    
    - name: Install dependencies
      run: sudo apt install build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu bc
    
    - name: Create EDK2 workspace
      run: mkdir /home/runner/work/EDK2WorkDir
      
    - name: Build edk2-ginkgo
      run: |
        cd /home/runner/work/EDK2WorkDir/
        git clone https://github.com/vicenteicc2008/edk2-woa32-arm64.git
        cd edk2-woa32-arm64
        git clone https://github.com/Tianocore/edk2.git --recursive
        git clone https://github.com/tianocore/edk2-platforms.git
        export PACKAGES_PATH=$PWD/../edk2:$PWD/../edk2-platforms:$PWD
        export WORKSPACE=$PWD/workspace
        . ../edk2/edksetup.sh
        GCC5_AARCH64_PREFIX=aarch64-linux-gnu- build -s -n 0 -a AARCH64 -t GCC5 -p RedmiNote8Pkg/RedmiNote8Pkg.dsc
        gzip -c < workspace/Build/RedmiNote8Pkg/DEBUG_GCC5/FV/REDMINOTE8PKG_UEFI.fd >uefi_image
        cat ginkgo.dtb >>uefi_image
        abootimg --create boot-ginkgo.img -k uefi_image -r ramdisk-null -f bootimg.cfg
        
    - uses: actions/upload-artifact@v3
      with:
       name: boot-ginkgo.img
       path: /home/runner/work/EDK2WorkDir/boot-ginkgo.img
